#!/usr/bin/env node
// Embeds SKILL.md + cli.md into src/skill.generated.ts so the CLI has no
// runtime file dependency. Frontmatter is stripped; the body is used as a prompt.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const skillSrc = readFileSync(join(root, "SKILL.md"), "utf8");
const cliSrc = readFileSync(join(root, "cli.md"), "utf8");

const skill = skillSrc.replace(/^---\n[\s\S]*?\n---\n/, "").trimStart();
const cli = cliSrc.replace(/^---\n[\s\S]*?\n---\n/, "").trimStart();

const out = `// GENERATED by scripts/embed-skill.ts — do not edit by hand.
export const SKILL = ${JSON.stringify(skill)};
export const CLI_ADDENDUM = ${JSON.stringify(cli)};
`;

writeFileSync(join(root, "src/skill.generated.ts"), out);
console.log(
  `embedded skill: ${skill.length} chars, cli addendum: ${cli.length} chars`,
);
